{"_path":"/code/db/db2","_dir":"db","_draft":false,"_partial":false,"_locale":"","_empty":false,"title":"DB2","description":"","body":{"type":"root","children":[{"type":"element","tag":"h1","props":{"id":"db2"},"children":[{"type":"text","value":"DB2"}]},{"type":"element","tag":"h2","props":{"id":"db2跨库操作失败"},"children":[{"type":"text","value":"DB2跨库操作失败"}]},{"type":"element","tag":"p","props":{},"children":[{"type":"text","value":"使用命令"},{"type":"element","tag":"code-inline","props":{},"children":[{"type":"text","value":"ALTER TABLESPACE MAXDATA EXTEND ( ALL 500 )"}]},{"type":"text","value":"，但是之后还是会出现同样的报错"},{"type":"element","tag":"a","props":{"href":"https://www.toolbox.com/tech/data-management/question/exception-when-importing-using-the-move-command-050911/","rel":["nofollow"]},"children":[{"type":"text","value":"参考的这个"}]}]}],"toc":{"title":"","searchDepth":2,"depth":2,"links":[{"id":"db2跨库操作失败","depth":2,"text":"DB2跨库操作失败"}]}},"_type":"markdown","_id":"content:3.code:db:db2.md","_source":"content","_file":"3.code/db/db2.md","_extension":"md"}